services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar-standalone
    ports:
      - "6650:6650"   # Pulsar broker port
      - "8080:8080"   # Pulsar admin port
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m
    command: bin/pulsar standalone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/v2/brokers/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf

volumes:
  pulsar_data:
  pulsar_conf:
